#Verify pg: 13

In [ ]:
import numpy as np
zeros_arr = np.zeros ((2 ,3) )
print (" A zeros array is \n", zeros_arr ,"with dimensions ", zeros_arr.shape , "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions  (2, 3) 



#Problem 1: Array Creation

In [ ]:
import numpy as np
empty_arr = np.empty ((2,2))
print(empty_arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
import numpy as np
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
shape = (3,2)
fill_value = 7
filled_array = np.full(shape, fill_value)
print(filled_array)

[[7 7]
 [7 7]
 [7 7]]


In [ ]:
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_array = np.zeros_like(original_array)
print(zeros_array)

[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])
ones_array = np.ones_like(original_array)
print(ones_array)

[[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


#Problem 2: Array Multiplication

In [ ]:
import numpy as np
array_range = np.arange(10,50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
array_1d = np.arange(9)
matrix_3x3 = array_1d.reshape((3, 3))
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
random_array = np.random.random(30)
mean_value = random_array.mean()
print(mean_value)

0.4991112466861205


In [ ]:
random_array = np.random.rand(10, 10)
min_value = random_array.min()
max_value = random_array.max()
print(min_value, max_value)
print(random_array)

0.015864800503935683 0.9998245794894772
[[0.56144838 0.03775893 0.97172843 0.57873441 0.7200887  0.34005287
  0.76140852 0.26044768 0.8724206  0.39820864]
 [0.03410753 0.94208612 0.88025172 0.2335521  0.13017301 0.44945815
  0.57306085 0.26857377 0.87341642 0.24383394]
 [0.0158648  0.24757142 0.30653409 0.1152858  0.29929569 0.77103635
  0.26927519 0.30548458 0.9120841  0.79305353]
 [0.33845597 0.9566596  0.72089565 0.0910111  0.86113352 0.50342478
  0.60868283 0.68744041 0.71191051 0.99982458]
 [0.70441796 0.96599908 0.25660554 0.25549391 0.80228145 0.21643031
  0.5266644  0.67133862 0.89676411 0.7915063 ]
 [0.70892537 0.64220677 0.53419407 0.65824505 0.19371475 0.5333867
  0.1500247  0.42378529 0.72845159 0.69081831]
 [0.44514087 0.25963918 0.82893314 0.93078019 0.32257581 0.99815416
  0.1246541  0.05993669 0.01965389 0.96073892]
 [0.60729099 0.67770386 0.98175687 0.73727078 0.91334915 0.65067024
  0.20460282 0.12097988 0.42990976 0.6629834 ]
 [0.97994465 0.56970603 0.45339611 0.1444

In [ ]:
zeros_array = np.zeros(10)
zeros_array[4] = 1
print(zeros_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [ ]:
shape = (5,5)
array_2d = np.ones(shape, dtype=int)
array_2d[1:-1, 1:-1] = 0
print(array_2d)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem 3: Array Operations

In [ ]:
x = np.array([[1,2], [3,5]])
y = np.array([[5,6], [7,8]])
v = np.array([9,10])
w = np.array([11,12])
add_xy = x + y
add_vw = v + w

sub_xy = x - y
sub_vw = v - w

mult_xy = x * y
mult_vw = v * w

sq_x = x**2
sq_y = y**2

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v[:, np.newaxis], w[:, np.newaxis]), axis=1)



#Problem 4: Matrix Operation

In [ ]:
import numpy as np

A = np.array([[3,4], [7,8]])
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print(I)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print(AB)
print(BA)

[[23 13]
 [51 29]]
[[36 44]
 [13 16]]


In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
BT_AT = np.dot(B_T, A_T)

print(AB_T)
print(BT_AT)

[[23 51]
 [13 29]]
[[23 51]
 [13 29]]


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print(x)

[ 2.  1. -2.]


In [ ]:

A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
b = np.array([-1, -3, 9])


x = np.linalg.solve(A, b)

print(x)

[ 2.  1. -2.]
